### ISSUE TITLE
Any chance to update the source to 0.7.1 release in fileforums?

### ISSUE THREAD

**Issue by sysbite** [Razor12911/xtool#6]
Not a bug report, just a request to update the source code to 0.7.1 from the fileforums release if possible.

Great work and piece of software, thanks for this.

**Comment by Razor12911** [comment]
Hi, the source of xtool is currently being worked in preparation for 0.7.2 release and as such it is currently in a broken state however for the next update the source here on github will be updated.

**Comment by sysbite** [comment]
Just saw the update, thanks a lot! 3b0bf1fe473099ec29098d1aeda777027d4554bd
