### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Adversarian** [Razor12911/xtool#7]
Hi. Thanks for your tremendous work!
I cannot seem to find the documentation for this tool although you said on another forum that it exists. Could you kindly please point me in the right direction?

**Comment by Razor12911** [comment]
Hi, there's a file that comes with the releases "xtool.chm", this is the documentation, though outdated it should explain the basics of the program.

**Comment by Adversarian** [comment]
Thank you for the prompt response. Closing the issue.
